version: 2

jobs:
  deployment:
    working_directory: ~/appkit
    docker:
      - image: circleci/node:6

    steps:
      - checkout
      - run: npm set progress=false
      - run: make release

workflows:
  version: 2
  workflow:
    jobs:
      - deployment
